apiVersion: v1
kind: Service
metadata:
  name: {{ template "cestzam.fullname" . }}
  labels:
{{ include "cestzam.labels" . | indent 4 }}
    app.kubernetes.io/component: cestzam
  {{- if .Values.service.extraLabels }}
{{ toYaml .Values.service.extraLabels | indent 4 }}
  {{- end }}

  {{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}

spec:
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . | quote }}
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
  {{- end }}


  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cestzam
  type: {{ .Values.service.type }}

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  {{ if .Values.deployment.debug.enabled }}
    - name: debug
      protocol: TCP
      port: 8787
      targetPort: 8787
  {{ end }}
